spring:
  application:
    name: reminderActeAuto
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  config:
    import: optional:file:.env[.properties]
  main:
    banner-mode: off

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
    show-sql: true


resend:
  api:
    key: ${RESEND_API_KEY}
  from:
    email: ${RESEND_FROM_EMAIL}
app.jwt.secret: ${JWT_SECRET}


